id: I993CC4DC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:06:24+00:00'
last_modified: '2022-06-08T09:49:46.072845+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2542
  title: ལྕེ་བཙུན་སྙིང་ཐིག་གི་ཁྱད་པར་གྱི་ཁྲིད་ཡིག་ལམ་བཟང་ཡེ་ཤེས་སྙིང་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    492E:
      image_group_id: I1CZ2710
      title: Volume 1 of lce btsun snying thig gi khyad par gyi khrid yig lam bzang
        ye shes snying po
      total_pages: 248
      order: 1
      base_file: 492E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
