id: P006985
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ2542
  title: ལྕེ་བཙུན་སྙིང་ཐིག་གི་ཁྱད་པར་གྱི་ཁྲིད་ཡིག་ལམ་བཟང་ཡེ་ཤེས་སྙིང་པོ
  author: ''
  volumes:
    e70415b8d35f448e8e57bbbeb1da2be0:
      image_group_id: I1CZ2710
      title: ''
      volume_number: 1
      total_pages: 248
ebook_metadata:
  title: ལྕེ་བཙུན་སྙིང་ཐིག་གི་ཁྱད་པར་གྱི་ཁྲིད་ཡིག་ལམ་བཟང་ཡེ་ཤེས་སྙིང་པོ
  author: ''
  sku: P006985
  cover: cover.jpg
  layers:
  - pagination
