id: P006985
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:34:25.661638
source_metadata:
  id: bdr:W1CZ2542
  title: ལྕེ་བཙུན་སྙིང་ཐིག་གི་ཁྱད་པར་གྱི་ཁྲིད་ཡིག་ལམ་བཟང་ཡེ་ཤེས་སྙིང་པོ
  author: ''
  volumes:
    c711f4d5d9ff4cd89983783c3cae0e16:
      image_group_id: I1CZ2710
      title: Volume 1 of lce btsun snying thig gi khyad par gyi khrid yig lam bzang
        ye shes snying po
      volume_number: 1
      total_pages: 248
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
